BEGIN TRANSACTION;
SET search_path TO main;
DO $$
    DECLARE
        tgid INT2;
        tid INT2;

        en_locale int2 = (SELECT locale_id FROM main.locales WHERE code = 'ren');
        ru_locale int2 = (SELECT locale_id FROM main.locales WHERE code = 'ru');
    BEGIN
	-- IT --
	INSERT INTO main.tag_groups (label) VALUES ('IT') RETURNING tag_group_id INTO tgid;
	INSERT INTO main.tag_groups_l10n (tag_group_id, locale_id, data) VALUES (tgid, ru_locale, '{"label": "ИТ"}');
	INSERT INTO main.tags (label, tag_group_id) VALUES ('A# .NET', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('A# (Axiom)', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('A-0 System', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('A+', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('A++', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ABAP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ABC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ABC ALGOL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ABLE', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ABSET', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ABSYS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ACC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Accent', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Ace DASL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ACL2', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ACT-III', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Action!', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ActionScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Ada', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Adenine', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Agda', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Agilent VEE', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Agora', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('AIMMS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Alef', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ALF', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ALGOL 58', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ALGOL 60', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ALGOL 68', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ALGOL W', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Alice', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Alma-0', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('AmbientTalk', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Amiga E', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('AMOS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('AMPL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('APL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('App Inventor for Android''s visual block language', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('AppleScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Arc', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ARexx', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Argus', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('AspectJ', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Assembly language', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ATS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Ateji PX', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('AutoHotkey', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Autocoder', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('AutoIt', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('AutoLISP / Visual LISP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Averest', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('AWK', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Axum', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('B', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Babbage', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Bash', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('BASIC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('bc', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('BCPL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('BeanShell', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Batch (Windows/Dos)', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Bertrand', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('BETA', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Bigwig', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Bistro', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('BitC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('BLISS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Blue', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Bon', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Boo', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Boomerang', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Bourne shell', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('bash', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ksh', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('BREW', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('BPEL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('C', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('C--', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('C++', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('C#', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('C/AL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Caché ObjectScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('C Shell', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Caml', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Candle', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Cayenne', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CDuce', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Cecil', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Cel', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Cesil', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Ceylon', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CFEngine', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CFML', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Cg', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Ch', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Chapel', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CHAIN', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Charity', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Charm', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Chef', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CHILL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CHIP-8', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('chomski', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ChucK', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CICS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Cilk', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Claire', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Clarion', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Clean', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Clipper', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CLIST', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Clojure', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CLU', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CMS-2', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('COBOL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Cobra', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CODE', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CoffeeScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Cola', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ColdC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ColdFusion', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('COMAL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Combined Programming Language', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('COMIT', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Common Intermediate Language', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Common Lisp', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('COMPASS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Component Pascal', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Constraint Handling Rules', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Converge', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Cool', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Coq', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Coral 66', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Corn', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CorVision', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('COWSEL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CPL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('csh', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CSP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Csound', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CUDA', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Curl', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Curry', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Cyclone', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Cython', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('D', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('DASL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Dart', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('DataFlex', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Datalog', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('DATATRIEVE', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('dBase', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('dc', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('DCL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Deesel', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Delphi', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('DinkC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('DIBOL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Dog', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Draco', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('DRAKON', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Dylan', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('DYNAMO', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('E', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('E#', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Ease', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Easy PL/I', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Easy Programming Language', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('EASYTRIEVE PLUS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ECMAScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Edinburgh IMP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('EGL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Eiffel', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ELAN', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Elixir', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Elm', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Emacs Lisp', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Emerald', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Epigram', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('EPL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Erlang', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('es', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Escapade', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Escher', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ESPOL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Esterel', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Etoys', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Euclid', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Euler', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Euphoria', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('EusLisp Robot Programming Language', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CMS EXEC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('EXEC 2', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Executable UML', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('F', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('F#', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Factor', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Falcon', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Fancy', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Fantom', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('FAUST', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Felix', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Ferite', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('FFP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Fjölnir', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('FL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Flavors', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Flex', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('FLOW-MATIC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('FOCAL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('FOCUS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('FOIL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('FORMAC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('@Formula', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Forth', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Fortran', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Fortress', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('FoxBase', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('FoxPro', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('FP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('FPr', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Franz Lisp', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Frege', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('F-Script', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('FSProg', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('G', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Google Apps Script', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Game Maker Language', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GameMonkey Script', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GAMS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GAP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('G-code', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Genie', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GDL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Gibiane', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GJ', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GEORGE', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GLSL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GNU E', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GM', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Go', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Go!', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GOAL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Gödel', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Godiva', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GOM (Good Old Mad)', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Goo', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Gosu', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GOTRAN', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GPSS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GraphTalk', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('GRASS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Groovy', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Hack (programming language)', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('HAL/S', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Hamilton C shell', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Harbour', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Hartmann pipelines', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Haskell', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Haxe', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('High Level Assembly', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('HLSL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Hop', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Hope', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Hugo', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Hume', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('HyperTalk', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('IBM Basic assembly language', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('IBM HAScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('IBM Informix-4GL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('IBM RPG', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ICI', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Icon', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Id', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('IDL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Idris', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('IMP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Inform', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Io', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Ioke', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('IPL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('IPTSCRAE', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ISLISP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ISPF', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ISWIM', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('J', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('J#', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('J++', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('JADE', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Jako', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('JAL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Janus', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('JASS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Java', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('JavaScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('JCL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('JEAN', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Join Java', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('JOSS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Joule', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('JOVIAL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Joy', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('JScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('JScript .NET', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('JavaFX Script', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Julia', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Jython', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('K', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Kaleidoscope', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Karel', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Karel++', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('KEE', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Kixtart', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('KIF', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Kojo', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Kotlin', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('KRC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('KRL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('KUKA', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('KRYPTON', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('L', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('L# .NET', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LabVIEW', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Ladder', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Lagoona', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LANSA', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Lasso', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LaTeX', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Lava', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LC-3', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Leda', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Legoscript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LIL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LilyPond', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Limbo', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Limnor', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LINC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Lingo', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Linoleum', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LIS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LISA', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Lisaac', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Lisp', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Lite-C', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Lithe', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Little b', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Logo', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Logtalk', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LPC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LSE', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LSL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LiveCode', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LiveScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Lua', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Lucid', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Lustre', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('LYaPAS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Lynx', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('M2001', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('M4', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Machine code', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MAD', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MAD/I', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Magik', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Magma', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('make', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Maple', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MAPPER', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MARK-IV', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Mary', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MASM Microsoft Assembly x86', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Mathematica', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MATLAB', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Maxima', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Macsyma', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Max', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MaxScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Maya (MEL)', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MDL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Mercury', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Mesa', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Metacard', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Metafont', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MetaL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Microcode', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MicroScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MIIS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MillScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MIMIC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Mirah', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Miranda', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MIVA Script', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ML', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Moby', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Model 204', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Modelica', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Modula', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Modula-2', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Modula-3', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Mohol', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MOO', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Mortran', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Mouse', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MPD', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('CIL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MSL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('MUMPS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('NASM', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('NATURAL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Napier88', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Neko', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Nemerle', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('nesC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('NESL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Net.Data', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('NetLogo', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('NetRexx', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('NewLISP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('NEWP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Newspeak', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('NewtonScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('NGL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Nial', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Nice', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Nickle', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Nim', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('NPL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Not eXactly C', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Not Quite C', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('NSIS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Nu', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('NWScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('NXT-G', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('o:XML', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Oak', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Oberon', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Obix', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('OBJ2', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Object Lisp', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ObjectLOGO', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Object REXX', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Object Pascal', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Objective-C', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Objective-J', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Obliq', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Obol', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('OCaml', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('occam', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('occam-π', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Octave', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('OmniMark', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Onyx', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Opa', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Opal', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('OpenCL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('OpenEdge ABL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('OPL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('OPS5', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('OptimJ', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Orc', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ORCA/Modula-2', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Oriel', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Orwell', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Oxygene', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Oz', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('P#', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ParaSail (programming language)', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PARI/GP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Pascal', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Pawn', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PCASTL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PCF', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PEARL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PeopleCode', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Perl', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PDL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PHP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Phrogram', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Pico', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Picolisp', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Pict', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Pike', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PIKT', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PILOT', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Pipelines', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Pizza', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PL-11', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PL/0', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PL/B', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PL/C', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PL/I', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PL/M', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PL/P', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PL/SQL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PL360', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PLANC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Plankalkül', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Planner', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PLEX', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PLEXIL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Plus', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('POP-11', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PostScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PortablE', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Powerhouse', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PowerBuilder', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PowerShell', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PPL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Processing', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Processing.js', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Prograph', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PROIV', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Prolog', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PROMAL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Promela', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PROSE modeling language', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('PROTEL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ProvideX', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Pro*C', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Pure', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Python', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Q (equational programming language)', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Q (programming language from Kx Systems)', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Qalb', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('QtScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('QuakeC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('QPL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('R', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('R++', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Racket', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('RAPID', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Rapira', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Ratfiv', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Ratfor', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('rc', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('REBOL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Red', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Redcode', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('REFAL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Reia', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Revolution', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('rex', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('REXX', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Rlab', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('RobotC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ROOP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('RPG', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('RPL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('RSL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('RTL/2', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Ruby', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('RuneScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Rust', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('S', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('S2', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('S3', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('S-Lang', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('S-PLUS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SA-C', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SabreTalk', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SAIL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SALSA', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SAM76', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SAS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SASL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Sather', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Sawzall', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SBL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Scala', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Scheme', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Scilab', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Scratch', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Script.NET', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Sed', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Seed7', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Self', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SenseTalk', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SequenceL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SETL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Shift Script', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SIMPOL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SIGNAL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SiMPLE', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SIMSCRIPT', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Simula', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Simulink', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SISAL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SLIP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SMALL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Smalltalk', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Small Basic', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SML', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Snap!', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SNOBOL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SPITBOL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Snowball', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SOL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Span', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SPARK', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Speedcode', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SPIN', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SP/k', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SPS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Squeak', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Squirrel', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SR', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('S/SL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Stackless Python', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Starlogo', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Strand', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Stata', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Stateflow', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Subtext', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SuperCollider', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SuperTalk', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Swift (Apple programming language)', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Swift (parallel scripting language)', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SYMPL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SyncCharts', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('SystemVerilog', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('T', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TACL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TACPOL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TADS', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TAL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Tcl', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Tea', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TECO', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TELCOMP', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TeX', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TEX', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TIE', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Timber', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TMG', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Tom', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TOM', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Topspeed', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TPU', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Trac', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TTM', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('T-SQL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TTCN', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Turing', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TUTOR', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TXL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('TypeScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Turbo C++', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Ubercode', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('UCSD Pascal', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Umple', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Unicon', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Uniface', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('UNITY', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Unix shell', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('UnrealScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Vala', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('VBA', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('VBScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Verilog', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('VHDL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Visual Basic', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Visual Basic .NET', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Visual DataFlex', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Visual DialogScript', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Visual Fortran', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Visual FoxPro', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Visual J++', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Visual J#', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Visual Objects', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Visual Prolog', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('VSXu', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Vvvv', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('WATFIV, WATFOR', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('WebDNA', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('WebQL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Windows PowerShell', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Winbatch', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Wolfram', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Wyvern', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('X++', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('X#', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('X10', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('XBL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('XC', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('XMOS architecture', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('xHarbour', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('XL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Xojo', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('XOTcl', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('XPL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('XPL0', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('XQuery', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('XSB', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('XSLT', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('XPath', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Xtend', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Yorick', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('YQL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Z notation', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('Zeno', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ZOPL', tgid);
	INSERT INTO main.tags (label, tag_group_id) VALUES ('ZPL', tgid);

END $$;
COMMIT;
